sonar.organization=Enzo
sonar.projectKey=passguard-ci
sonar.projectName=PassGuard CI
sonar.sourceEncoding=UTF-8

sonar.sources=app,frontend/src
sonar.tests=tests,frontend/src
sonar.test.inclusions=tests/**/*.py,frontend/src/**/*.test.tsx

sonar.exclusions=frontend/dist/**,frontend/node_modules/**,frontend/*.tsbuildinfo,**/__pycache__/**,.venv/**
sonar.python.version=3.11
